export const GlobalConstants = {
  brandName : "Memofeed",
  brandTagLine1 : "Give life to your stories/memories",
  brandTagLine2 : "Where Memories Live.",
  brandTagLine3: "Share What Matters.",
  githubLink : "https://github.com/bharatpaliwal-169",
  author : "Bharat Paliwal",
  footerContent : "Made with ❤️ by ",
  logout : "Logout",
  login : "Login/SignUp",
  defaultUser : "Hey! User",
  profile : "Profile",
  search : "Search",
  defaultImage : 'https://user-images.githubusercontent.com/194400/49531010-48dad180-f8b1-11e8-8d89-1e61320e1d82.png',
  cancel : "Cancel",
  delete : "Delete",
  deleteAlertMessage : "You cannot undo this action; Kindly be very sure about it.",
  creator : "Author :",
  openSettings : "Open Settings",
  notFound : "404 NOT FOUND !!",
  notFoundDesp: "Something you are looking for does not exist.",
  backToHome: "Back To Home",
  confirmLogout: "Do you want to logout ?",
  cancel : "Cancel",
  
}